### PR TITLE
Client Login via device authorization flow

### PR DESCRIPTION
**Pull request by mlsmaycon**
The client will fetch the device authorization flow information from management and will use it to login using our hosted provider.

* moved the OAuth package to internal as we only have one option
* use management URL in the service configuration
* Added SSO login to UI and CLI clients
* Check if the client is logged in when starting UI
* retrieve device authorization flow information from management

### CODE REVIEW

**Comment by braginini** [comment]
@mlsmaycon do we really need --sso?

When there is no setup key provided then it should be interactive login by default, right?

**Comment by mlsmaycon** [comment]
> @mlsmaycon do we really need --sso?
> 
> When there is no setup key provided then it should be interactive login by default, right?

we do for now, for self-hosted users, we will make it default in new releases

**Comment by braginini** [comment]
@mlsmaycon 

When doing first run:
`sudo rm -rf /etc/wiretrustee/config.json && sudo systemctl restart wiretrustee.service`

Log output. The PermissionDenied error is okay, right?  We first try to log in and see, that the device has not been registered. 
Maybe we shouldn't out it? It is a part of normal logic, not something abnormal. Or maybe we could just state in log that the status is LoginRequired.
```
time="2022-05-12T09:19:37+02:00" level=info msg="starting service"
time="2022-05-12T09:19:37+02:00" level=info msg="generating new config /etc/wiretrustee/config.json"
time="2022-05-12T09:19:37+02:00" level=info msg="started daemon server: /var/run/wiretrustee.sock"
time="2022-05-12T09:19:37+02:00" level=error msg="peer registration required. Please run wiretrustee login command first"
time="2022-05-12T09:19:37+02:00" level=warning msg="rpc error: code = PermissionDenied desc = provided peer with the key wgPubKey yv1sR4rlyEON8EwZbgt7h3kul8j5IF3ED31wWSJahxM= is not registered"
```

**Comment by braginini** [comment]
@mlsmaycon 

When doing the first run and then
 `wiretrustee up --management-url http://localhost:33073`

There is an error in the log:
```
time="2022-05-12T09:24:22+02:00" level=info msg="starting service"
time="2022-05-12T09:24:22+02:00" level=info msg="generating new config /etc/wiretrustee/config.json"
time="2022-05-12T09:24:22+02:00" level=info msg="started daemon server: /var/run/wiretrustee.sock"
time="2022-05-12T09:24:22+02:00" level=error msg="peer registration required. Please run wiretrustee login command first"
time="2022-05-12T09:24:22+02:00" level=warning msg="rpc error: code = PermissionDenied desc = provided peer with the key wgPubKey AjjCR5QapL4tMT2qLFUk5E/t8zpcwDKl2w8yuAmhY1k= is not registered"
time="2022-05-12T09:24:27+02:00" level=info msg="new Management URL provided, updated to http://localhost:33073 (old value https://api.wiretrustee.com:33073)"
time="2022-05-12T09:24:27+02:00" level=info msg="new Admin Panel URL provided, updated to https://app.netbird.io (old value <nil>)"
time="2022-05-12T09:24:32+02:00" level=info msg="peer has been successfully registered on Management Service"
time="2022-05-12T09:24:33+02:00" level=info msg="connected to the Signal Service stream"
time="2022-05-12T09:24:33+02:00" level=info msg="Wiretrustee engine started, my IP is: 100.64.0.3/24"
time="2022-05-12T09:24:33+02:00" level=info msg="connected to the Management Service stream"
time="2022-05-12T09:24:33+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
time="2022-05-12T09:24:34+02:00" level=info msg="connected to the Management Service stream"
time="2022-05-12T09:24:34+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
time="2022-05-12T09:24:35+02:00" level=info msg="connected to the Management Service stream"
time="2022-05-12T09:24:35+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
time="2022-05-12T09:24:36+02:00" level=info msg="connected to the Management Service stream"
time="2022-05-12T09:24:36+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
time="2022-05-12T09:24:36+02:00" level=info msg="connected to the Management Service stream"
time="2022-05-12T09:24:36+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
time="2022-05-12T09:24:37+02:00" level=info msg="connected to the Management Service stream"
time="2022-05-12T09:24:37+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
time="2022-05-12T09:24:37+02:00" level=info msg="connected to the Management Service stream"
time="2022-05-12T09:24:37+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
```

**Comment by mlsmaycon** [comment]
> @mlsmaycon
> 
> When doing the first run and then `wiretrustee up --management-url http://localhost:33073`
> 
> There is an error in the log:
> 
> ```
> time="2022-05-12T09:24:22+02:00" level=info msg="starting service"
> time="2022-05-12T09:24:22+02:00" level=info msg="generating new config /etc/wiretrustee/config.json"
> time="2022-05-12T09:24:22+02:00" level=info msg="started daemon server: /var/run/wiretrustee.sock"
> time="2022-05-12T09:24:22+02:00" level=error msg="peer registration required. Please run wiretrustee login command first"
> time="2022-05-12T09:24:22+02:00" level=warning msg="rpc error: code = PermissionDenied desc = provided peer with the key wgPubKey AjjCR5QapL4tMT2qLFUk5E/t8zpcwDKl2w8yuAmhY1k= is not registered"
> time="2022-05-12T09:24:27+02:00" level=info msg="new Management URL provided, updated to http://localhost:33073 (old value https://api.wiretrustee.com:33073)"
> time="2022-05-12T09:24:27+02:00" level=info msg="new Admin Panel URL provided, updated to https://app.netbird.io (old value <nil>)"
> time="2022-05-12T09:24:32+02:00" level=info msg="peer has been successfully registered on Management Service"
> time="2022-05-12T09:24:33+02:00" level=info msg="connected to the Signal Service stream"
> time="2022-05-12T09:24:33+02:00" level=info msg="Wiretrustee engine started, my IP is: 100.64.0.3/24"
> time="2022-05-12T09:24:33+02:00" level=info msg="connected to the Management Service stream"
> time="2022-05-12T09:24:33+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
> time="2022-05-12T09:24:34+02:00" level=info msg="connected to the Management Service stream"
> time="2022-05-12T09:24:34+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
> time="2022-05-12T09:24:35+02:00" level=info msg="connected to the Management Service stream"
> time="2022-05-12T09:24:35+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
> time="2022-05-12T09:24:36+02:00" level=info msg="connected to the Management Service stream"
> time="2022-05-12T09:24:36+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
> time="2022-05-12T09:24:36+02:00" level=info msg="connected to the Management Service stream"
> time="2022-05-12T09:24:36+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
> time="2022-05-12T09:24:37+02:00" level=info msg="connected to the Management Service stream"
> time="2022-05-12T09:24:37+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
> time="2022-05-12T09:24:37+02:00" level=info msg="connected to the Management Service stream"
> time="2022-05-12T09:24:37+02:00" level=error msg="failed handling an update message received from Management Service: wgtypes: failed to parse base64-encoded key: illegal base64 data at input byte 44"
> ```

Was a local issue with peers in testing account

**Pull request merged**
