### PR TITLE
Add support for refreshing signing keys on expiry

### PR DESCRIPTION
**Pull request by bcmmbaga**
## Describe your changes
Introduces a new flag `--idp-sign-key-refresh-enabled` that enables the Cache-Control header to be checked when fetching signing keys to determine the rotation period for signing keys. This feature will automatically refresh the signing key upon its expiry.

## Issue ticket number and link
* Add support for rotating signing keys on expiry  ([#806][i806])

[i806]: https://github.com/netbirdio/netbird/issues/806
### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Thanks for the quick response!

Although, I believe this should be the default behavior and not a flag. Most, if not all, IdPs rotate the signing keys after certain time intervals so it'll make sense to enable it by default.

**Comment by bcmmbaga** [comment]
> Although, I believe this should be the default behavior and not a flag. Most, if not all, IdPs rotate the signing keys after certain time intervals so it'll make sense to enable it by default.

some IDP's may not rotate their signing keys automatically, which means that enabling this feature by default could result in additional calls to the endpoint every time a user requests access, potentially leading to rate limiting calls.

**Comment by Thunderbottom** [comment]
I believe a better way to do this would be to check if the cache-control header exists with the expiry defined the first time netbird starts, and then use that to check locally every time someone tries to access. There's no need for another flag for doing that.

**Comment by pascal-fischer** [comment]
I was reviewing the code and it looks good so far but if I am not mistaken we fetch the keys once on startup. When they are expired every following token validation will send a get request to get the new keys. Is there a way for us to store the refreshed keys? so we only request new keys once and store them until next expiration?

I also think it would be a good idea to set the key rotation as the default behaviour, but only if we keep the request count low.

**Comment by bcmmbaga** [comment]
> I was reviewing the code and it looks good so far but if I am not mistaken we fetch the keys once on startup. When they are expired every following token validation will send a get request to get the new keys.

Currently, the keys are only retrieved once during startup and are not retrieved again after they have expired for Identity Providers that have automatic key rotation.

>  Is there a way for us to store the refreshed keys? so we only request new keys once and store them until next expiration?

Identity Providers that have a  auto key rotation in x interval  will also require the retrieval of a new key after it has expired

**Review by pascal-fischer — DISMISSED** [review]

**Review by pascal-fischer — APPROVED** [review]

**Review by pascal-fischer — DISMISSED** [review]

**Review by pascal-fischer — APPROVED** [review]

**Pull request merged**
