### PR TITLE
support to configure extra blacklist of iface in "up" command

### PR DESCRIPTION
**Pull request by hoozecn**
## Describe your changes

we can configure extra blacklist of iface in "up" command instead of editing config file

### Checklist
- [*] Is a feature enhancement

### CODE REVIEW

**Comment by hoozecn** [comment]
Yes. we use netbird client as Daemonset in Kubernetes so that the selected nodes will work as gateways of the cluster. the change in PR is enough for us and works well.

For your point, I'm happy to see to make it be configurable too in traditional way when we run `netbird up`  in a "normal" node for instance a bare-metal node.  I would like to check the codebase to see how to make it possible with gRPC.

But before that, do you think it worth a try?

**Comment by braginini** [comment]
> Yes. we use netbird client as Daemonset in Kubernetes so that the selected nodes will work as gateways of the cluster. the change in PR is enough for us and works well.
> 
> For your point, I'm happy to see to make it be configurable too in traditional way when we run `netbird up` in a "normal" node for instance a bare-metal node. I would like to check the codebase to see how to make it possible with gRPC.
> 
> But before that, do you think it worth a try?

I will sync with the team tomorrow morning and get back to you after. Thank you!

**Comment by dkrhodes** [comment]
Update the PR to configure in daemon mode

**Comment by hoozecn** [comment]
@braginini hey man, thanks for you sync. I have update the pr to support the daemon mode. 

Just find another PR not merged #1586. Seems it's going to support to configure InterfaceBlacklist too. 

The ExtraIFaceBlacklist option make help people avoid to provide the default blacklist in the command line. But use InterfaceBlacklist will be more explicit. 

Which do you think is better?

**Review by pappz — APPROVED** [review]

**Pull request merged**
