### PR TITLE
[management, client] Add access control support to network routes

### PR DESCRIPTION
**Pull request by bcmmbaga**
### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by roney492** [comment]
Any ETA on when this will be merged??

**Comment by fdisamuel** [comment]
I would like to know as well..😅

**Comment by braginini** [comment]
@roney492 @fdisamuel This PR is one of our top prios. Soon it will be merged, give us a couple of weeks :)

**Comment by fdisamuel** [comment]
Hey @braginini thank you for your answer, we are looking forward for it :D

**Comment by roney492** [comment]
Any update on this??

**Comment by roney492** [comment]
Any update on this?

**Comment by pernetz** [comment]
Not sure if I understand this feature request correctly. Is it meant to access a remote network computer (w/o netbird client) via IP from a computer (w/o netbird client) from a local network? I manage to networks with each having one netbird peer online. I want to use these peers to route traffic forward to both LANs. Network routes are properly set on both local routes, but I cannot reach the other side.

**Comment by mlsmaycon** [comment]
> Not sure if I understand this feature request correctly. Is it meant to access a remote network computer (w/o netbird client) via IP from a computer (w/o netbird client) from a local network? I manage to networks with each having one netbird peer online. I want to use these peers to route traffic forward to both LANs. Network routes are properly set on both local routes, but I cannot reach the other side.

@pernetz This feature is under review and testing now and should not affect your clients at this time. Can you please open a github issue with the problem?

**Review by pappz — APPROVED** [review]

**Review by mlsmaycon — APPROVED** [review]

**Pull request merged**
