### PR TITLE
Engine should restart and block more restarts

### PR DESCRIPTION
**Pull request by hurricanehrndz**
## Describe your changes
Block rapid restarts in succession for 3s.

## Issue ticket number and link
Possible fix for #2196 #2011
### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by lixmal** [comment]
What problem is this solving? Would increasing the timeout suffice?

**Comment by hurricanehrndz** [comment]
> What problem is this solving? Would increasing the timeout suffice?

Increasing the timeout might. The only difference between your approach and this approach is that engine restart is initiate and then blocked, meanwhile the current code base waits to restart. Either way as long as utun100 resource busy is no longer happening this can be closed

We should wait until @christian-schlichtherle or @fadyHemaya have responded to the issues to confirm 28.5+ and the current code base doesn't result in utun100 resource busy.

**Comment by lixmal** [comment]
> > What problem is this solving? Would increasing the timeout suffice?
> 
> The only difference between your approach and this approach is that engine restart is initiate and then blocked, meanwhile the current code base waits to restart.

We need to pick up the latest network state (routes), that's why we cannot just ignore changes for X seconds.
If we miss the latest change in a row of route changes we might set up routes pointing to the wrong thing and netbird might be broken. I don't might increasing the timeout, though.

**Comment by hurricanehrndz** [comment]
Good point, thank you for the clarification

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
