### PR TITLE
Add codespell job

### PR DESCRIPTION
**Pull request by mlsmaycon**
### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by Fantu** [comment]
@mlsmaycon I saw
```
with:
  only_warn: 1
```
that make job not failing but only report problem found, I think should be added so will not result in fail for result that should be added in exclusion

**Comment by Fantu** [comment]
@mlsmaycon the continue error I suppose can be for:
`Words are case sensitive based on **how they are written in the dictionary file**.`
so for:
`clientA ==> client`
if I understand good should be excluded "client" but if correct this seems to me bad thing that don't permit exclusion check of result instead (or in alternative)

**Comment by mlsmaycon** [comment]
> @mlsmaycon the continue error I suppose can be for:
> 
> > Words are case sensitive based on **how they are written in the dictionary file**.
> 
> so for: `clientA ==> client` if I understand good should be excluded "client" but if correct this seems to me bad thing that don't permit exclusion check of result instead (or in alternative)

trying that, thanks for the tip

**Comment by Fantu** [comment]
still fails, so seems there is a bug that should be reported
in the meantime I suggest you put
`only_warn: 1`

**Comment by Fantu** [comment]
try erro and clienta, all lower case

**Review by surik — APPROVED** [review]

**Pull request merged**
