### PR TITLE
Introducing NetBird Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [NetBird Guru](https://gurubase.io/g/netbird) to Gurubase. NetBird Guru uses the data from this repo and data from the [docs](https://docs.netbird.io/) to answer questions by leveraging the LLM.

In this PR, I showcased the "NetBird Guru", which highlights that NetBird now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable NetBird Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by mattish91** [comment]
Totally works, just managed to setup a ps1 script using your AI to automate the installation on Windows machines trough MDM system, works like a charm, and i can even use the same code to update it as well as it will automagically grab the latest version.

Your Guru AI is truely a Guru!

mkdir c:\TempPath
Invoke-WebRequest -Uri https://pkgs.netbird.io/windows/x64 -OutFile C:\TempPath\NetBird_Installer.exe
$installerPath = "C:\TempPath\NetBird_Installer.exe"
$setupID = "YOUR_ID_HERE"
Start-Process -FilePath $installerPath -ArgumentList "/S", "/setup-id=$setupID" -Wait
del C:\TempPath\NetBird_Installer.exe

**Comment by kursataktas** [comment]
Hey everyone, have you had a chance to check this out?

**Review by mlsmaycon — APPROVED** [review]

**Comment by kursataktas** [comment]
Hi everyone,

I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by kursataktas** [comment]
Hello Everyone,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

**Comment by mattish91** [comment]
> Hello Everyone,
> 
> We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.
> 
> The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).
> 
> You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

That would be an awesome feature to have in the documentation page, this because it's so much more knowledgeable than what you could get from the documentation alone. 

Like i said before, i were able to automate the entire installation of the Netbird Client using the Setup ID on Windows machines (automated trough RMM) using PowerShell alone with the Setup ID like i showed above, and it works really well. I were unable to find anything about that kind of setup using the documentation alone. 

By that time (not sure if it's added there still) i had no clue how the NetBird switch would turn out as i have both family members computers and servers relied on VPN configs to access my homelab that i manage from Immense/Remotely (now replaced entirely with NetBird) and updated everything to work tough NetBird configs instead.

**Comment by kursataktas** [comment]
Hello @mlsmaycon,

I want to share an exciting update about Gurubase. We've recently released several great features that I think you'll find interesting.

### 1. Slack & Discord Integration
You can now add your Guru as a bot to Slack and Discord, allowing you to ask questions instantly. More details here: [Discord Bot Integration](https://docs.gurubase.ai/integrations/discord-bot).

### 2. Analytics Dashboard
Track what your users ask your Guru and gain valuable insights. This feature is available on the "My Gurus" page. If you haven’t maintained your Guru yet, I highly recommend doing so to access your analytics. More information about claiming your Guru can be found [here](https://github.com/Gurubase/gurubase?tab=readme-ov-file#how-to-claim-a-guru).
image

### 3. API Support
All Guru functionalities are now accessible via API. You can ask questions, edit data sources, and more using our API endpoints. Here is the [API Doc](https://docs.gurubase.ai/api-reference/introduction).

### 4. Codebase Indexing
We now support indexing codebases from GitHub repositories to generate answers for related queries. This feature is available for select Gurus. If you don’t see the "Codebase Indexed" label on your Guru edit page and would like access, please let me know, I’d be happy to enable it for you!
image

Let me know if you have any questions or feedback!

**Comment by kursataktas** [comment]
Hey @mlsmaycon and @mattish91,

I wanted to update you that we’ve released the Gurubase GitHub bot.
This means you can now integrate your Guru into your repository,  so users can ask it questions directly through GitHub issues. By default, the Gurubase bot automatically responds to newly opened issues, but you can customize its behavior if needed.

You can see it in action in [this demo issue](https://github.com/Gurubase/gurubase/issues/248).
More information about the bot can be found [here](https://docs.gurubase.ai/integrations/github-bot).

gurubase-github-bot-demo

-----

_Note: As I mentioned in my first update on this thread, please let me know if you’d prefer not to receive updates here._

**Pull request merged**
