### PR TITLE
Get client ui locale on windows natively

### PR DESCRIPTION
**Pull request by lixmal**
## Describe your changes

Get the windows client ui local without powershell

## Issue ticket number and link

#2192
We're getting the locales on windows via powershell, that leads to a popup before starting netbird-ui.

### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by lixmal** [comment]
@Yxnt Can you verify that this PR doesn't affect the functionality please?

**Comment by Yxnt** [comment]
> @Yxnt Can you verify that this PR doesn't affect the functionality please?@Yxnt 能否请您确认该 PR 不会影响功能？

i will check it later. :)

**Comment by mlsmaycon** [comment]
> > @Yxnt Can you verify that this PR doesn't affect the functionality please?
> 
> i will check it later. :)

Hello @Yxnt, have you got the chance to validate the fix? We are planing to release a new version today with this.

**Comment by Yxnt** [comment]
> > > @Yxnt Can you verify that this PR doesn't affect the functionality please?
> > 
> > 
> > i will check it later. :)
> 
> Hello @Yxnt, have you got the chance to validate the fix? We are planing to release a new version today with this.

Sorry I've been busy the last couple of days, I've just looked at it and there's no problem, and the run window doesn't pop up when I run it either

**Review by Yxnt — APPROVED** [review]
everything is ok.

**Comment by mlsmaycon** [comment]
> > > > @Yxnt Can you verify that this PR doesn't affect the functionality please?
> > > 
> > > 
> > > i will check it later. :)
> > 
> > 
> > Hello @Yxnt, have you got the chance to validate the fix? We are planing to release a new version today with this.
> 
> Sorry I've been busy the last couple of days, I've just looked at it and there's no problem, and the run window doesn't pop up when I run it either

no worries, thanks for taking the time to double check on your end.

**Review by mlsmaycon — APPROVED** [review]

**Pull request merged**
