### PR TITLE
Add mipsle build to enable netbird for devices such as EdgeRouter X

### PR DESCRIPTION
**Pull request by ovidiuvio**
MIPSLE 

## Describe your changes
This enables running netbird on edgerouter x devices, which have mipsle processors.
### Checklist
- new build target for netbird client
- Tested on edgerouter x

### CODE REVIEW

**Comment by mlsmaycon** [comment]
@ovidiuvio thanks for your contribution. It looks very simple. 

Can you confirm that the build from the artifacts produced by our release workflow works for the mipsle platform you have? 

you can find them here: https://github.com/netbirdio/netbird/actions/runs/4919934285?pr=842

**Comment by ovidiuvio** [comment]
A few updates:

* binaries work on `Ubiquiti EdgeRouter X`
* .deb packages have the wrong arch set, so they can only be installed with:  `dpkg --force-architecture`

An other note here is that if `wireguard.ko` is not on the device, then go wireguard is used and that leads to a `kernel oom kill` of netbird after device locks up

So, a prerequisite for netbird on `EdgeRouter X' is this one:

[`wireguard-vyatta-ubnt`](https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20220627-1/e50-v2-v1.0.20220627-v1.0.20210914.deb)

Some speed tests between to `EdgeRouter X` devices:

Netbird with Wireguard GO: (this gets the router stuck)
```
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  5.08 MBytes  42.6 Mbits/sec    0    303 KBytes
[  5]   1.00-2.00   sec  5.02 MBytes  42.1 Mbits/sec    0    497 KBytes
[  5]   2.00-3.00   sec  5.20 MBytes  43.6 Mbits/sec    0    497 KBytes
[  5]   3.00-4.00   sec  4.28 MBytes  35.9 Mbits/sec    0    497 KBytes
[  5]   4.00-5.00   sec  4.47 MBytes  37.5 Mbits/sec    0    497 KBytes
[  5]   5.00-6.00   sec  4.22 MBytes  35.4 Mbits/sec    0    497 KBytes
[  5]   6.00-7.00   sec  4.47 MBytes  37.5 Mbits/sec    0    522 KBytes
[  5]   7.00-8.00   sec  5.02 MBytes  42.1 Mbits/sec    0    522 KBytes
[  5]   8.00-9.00   sec  5.08 MBytes  42.6 Mbits/sec    0    522 KBytes
[  5]   9.00-10.00  sec  5.02 MBytes  42.1 Mbits/sec    0    522 KBytes
```

Netbird with wireguard.ko

```
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  12.2 MBytes   102 Mbits/sec
[  5]   1.00-2.00   sec  15.2 MBytes   128 Mbits/sec
[  5]   2.00-3.01   sec  16.4 MBytes   137 Mbits/sec
[  5]   3.01-4.00   sec  17.3 MBytes   146 Mbits/sec
[  5]   4.00-5.00   sec  17.7 MBytes   148 Mbits/sec
[  5]   5.00-6.00   sec  17.3 MBytes   145 Mbits/sec
[  5]   6.00-7.00   sec  17.2 MBytes   145 Mbits/sec
[  5]   7.00-8.00   sec  18.1 MBytes   152 Mbits/sec
[  5]   8.00-9.00   sec  16.2 MBytes   136 Mbits/sec
[  5]   9.00-10.00  sec  17.4 MBytes   146 Mbits/sec
```

I'll take a look at the pipeline to see if I can get the .deb files to have the right arch set in metadata,
Otherwise we should just disable building them.

**Comment by braginini** [comment]
@ovidiuvio is there a stock WireGuard for this platform?

**Comment by ovidiuvio** [comment]
> Great Jo, @ovidiuvio Is there a stock WireGuard for this platform?

There is not as far as I am aware, but it is a very popular router choice.
It runs EdgeOS (Ubiquiti proprietary OS) - a fork of Vyatta (VyOS is the open source fork)

**Comment by ovidiuvio** [comment]
@mlsmaycon : I've added more common mips builds and moved them to a separate build stage that doesn't generate .deb, .rpm files.

At least the .deb files have incorrect architecture flag set in them by goreleaser.

Please review.

**Comment by ovidiuvio** [comment]
@mlsmaycon @braginini 

Can you guys take a look at the pipeline ?
Release_UI failed with internal error, but I have not changed anything related to it.

**Comment by mlsmaycon** [comment]
All good now @ovidiuvio

**Review by mlsmaycon — APPROVED** [review]
Thank you @ovidiuvio

**Pull request merged**
