### PR TITLE
[misc] Support rpm-ostree based distros in installation script

### PR DESCRIPTION
**Pull request by M0Rf30**
## Describe your changes
This add `rpm-ostree` binary detection in installation script and update `kardianos/service` module to lastest commits. It should close https://github.com/netbirdio/netbird/issues/1634

Latest commits of `kardianos/service` correctly detect and discriminate between `/etc` folders (init.d, systemd/system....)

### CODE REVIEW

**Comment by jkrogers9862** [comment]
I am not sure I understand how this will fix [#1634](https://github.com/netbirdio/netbird/issues/1634). 
Does rpm-ostree call this install script when installing? This looks like it just simple fixes allowing install from the install script which was missing until now. The problem is that an error occurs during the post-trans scripts.

**Comment by M0Rf30** [comment]
> I am not sure I understand how this will fix [#1634](https://github.com/netbirdio/netbird/issues/1634). Does rpm-ostree call this install script when installing? This looks like it just simple fixes allowing install from the install script which was missing until now. The problem is that an error occurs during the post-trans scripts.

postinst fails on `netbird service install`.

`service install` fails cause of non-updated service module.

plus, I add rpm-ostree support to install script in order to leverage the rpm packages and repo instead of binary archive

**Comment by M0Rf30** [comment]
> Why was it not a universal problem? On Silverblue, I could still install until I tried to install packages `libvirt` and `network-scripts`. Given the nature of the problem and the proposed solution, I would have thought it would be a 100% failure.
> 
> How can I get a rpm to locally install and test this?

need to generate an rpm with goreleaser, check the documentation

**Comment by mlsmaycon** [comment]
@M0Rf30 we are using a forked version of github.com/kardianos/service; see https://github.com/netbirdio/netbird/blob/92a0092ad5262a3687d64a42edbf0938e3872039/go.mod#L208

Can you make this PR only about adding rpm-ostree, or is the module update a requirement for it? if so, we will update the fork and update the module in a separate PR first.

**Comment by jkrogers9862** [comment]
> @M0Rf30 we are using a forked version of github.com/kardianos/service; see
> 
> https://github.com/netbirdio/netbird/blob/92a0092ad5262a3687d64a42edbf0938e3872039/go.mod#L208
> 
> Can you make this PR only about adding rpm-ostree, or is the module update a requirement for it? if so, we will update the fork and update the module in a separate PR first.

From my understanding the module update is what this Pull request is actually for to fix: #1634. I believe the author decided to also update the install script in addition as it was missing. The problem is that on Fedora Atomic-Based Operating Systems, netbird fails to install when certain packages are installed. On Silverblue, variants and on Fedora IoT and CoreOS, it can't be installed period because those packages are included in the base immutable-images which leaves the Docker variant as the only alternative on those systems.

It seems some updates were made to the kardiano/service which included fixes that solve the issue relating to the issue of installing.

**Comment by mlsmaycon** [comment]
> > @M0Rf30 we are using a forked version of github.com/kardianos/service; see
> > 
> > https://github.com/netbirdio/netbird/blob/92a0092ad5262a3687d64a42edbf0938e3872039/go.mod#L208
> > 
> > Can you make this PR only about adding rpm-ostree, or is the module update a requirement for it? if so, we will update the fork and update the module in a separate PR first.
> 
> From my understanding the module update is what this Pull Request is actually for to fix: #1634. I believe the author decided to also update the install script in addition as it was missing. The problem is that on Fedora Atomic-Based Operating Systems, `netbird` fails to be layered when certain packages are also layered. On Silverblue variants it fails to install when `libvirt` and `network-scripts` is layered and on Fedora IoT and CoreOS, it can't be layered period because parts of those packages are included in the base immutable-images which leaves the Docker variant as the only alternative on those systems.
> 
> It seems some updates were made to the kardiano/service which included fixes that solve the issue relating to the issue of installing. So if something is to be removed from this pull it should be the update to the install script.

I see, in this case it is better for us to upgrade the fork and update the go.mod and go.sum.

I will prepare the PR in a few hours

**Comment by M0Rf30** [comment]
> > > @M0Rf30 we are using a forked version of github.com/kardianos/service; see
> > > https://github.com/netbirdio/netbird/blob/92a0092ad5262a3687d64a42edbf0938e3872039/go.mod#L208
> > > 
> > > Can you make this PR only about adding rpm-ostree, or is the module update a requirement for it? if so, we will update the fork and update the module in a separate PR first.
> > 
> > 
> > From my understanding the module update is what this Pull Request is actually for to fix: #1634. I believe the author decided to also update the install script in addition as it was missing. The problem is that on Fedora Atomic-Based Operating Systems, `netbird` fails to be layered when certain packages are also layered. On Silverblue variants it fails to install when `libvirt` and `network-scripts` is layered and on Fedora IoT and CoreOS, it can't be layered period because parts of those packages are included in the base immutable-images which leaves the Docker variant as the only alternative on those systems.
> > It seems some updates were made to the kardiano/service which included fixes that solve the issue relating to the issue of installing. So if something is to be removed from this pull it should be the update to the install script.
> 
> I see, in this case it is better for us to upgrade the fork and update the go.mod and go.sum.
> 
> I will prepare the PR in a few hours

Already done here in the same time I've opened this

See
https://github.com/netbirdio/service/pull/2

**Comment by bcmmbaga** [comment]
@M0Rf30  The service PR is already merged can you bump the version in go.mod?

**Review by bcmmbaga — APPROVED** [review]

**Pull request merged**
