### PR TITLE
Add device flow scope.

### PR DESCRIPTION
**Pull request by aazf**
## Describe your changes

Most of IDP require a base scope, so add the openid as the base scope.

## Issue ticket number and link
Na

### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by mlsmaycon** [comment]
@aazf thanks for the contribution, we will test with auth0 and keycloak and then approve.

Can you share which idp you had the problem with so we can support users that run into the same issue.

**Comment by mlsmaycon** [comment]
> @mlsmaycon https://github.com/dexidp/dex

thanks @aazf 

I've enabled the workflows, can you update the failing tests?

**Comment by mlsmaycon** [comment]
Thanks @aazf

**Comment by mlsmaycon** [comment]
@aazf the Docker Compose Linux test fails because of some missing secrets.

**Comment by braginini** [comment]
> @mlsmaycon So how to fix it, or everything is fine.

That's okay. All good. We can ignore it now.
The docker compose test requires some secrets that are not available in forks. These are private to the netbird org.

**Review by mlsmaycon — APPROVED** [review]

**Pull request merged**
